In [2]:
import glob
from bs4 import BeautifulSoup
import os
import time
import datetime
import pandas as pd
import numpy as np
import bz2
pd.set_option('display.max_columns', 100)

# descomprimir Archivos

In [3]:
f_in = open("DataSui_ele_com_096.csv.gz", "rb")
f_out = open("DataSui_ele_com_096.csv", "wb")
f_out.write(bz2.decompress(f_in.read()))
f_out.close()
f_in.close()

In [4]:
FinalM = pd.read_csv(
    "./DataSui_ele_com_096.csv",      # relative python path to subdirectory
    sep=',',           # Tab-separated value file.
    #quotechar="'",        # single quote allowed as quote character
    #dtype={"salary": int},             # Parse the salary column as an integer 
    #usecols=['name', 'birth_date', 'salary'].   # Only load the three columns specified.
    #parse_dates=['birth_date'],     # Intepret the birth_date column as a date
    #skiprows=10,         # Skip the first 10 rows of the file
    na_values=''      # Take any '.' or '??' values as NA
)

In [5]:
FinalM

,Unnamed: 0,Age,Month,Site,Departamento,Municipio,Empresa,Estrato 1_Suscriptores,Estrato 2_Suscriptores,Estrato 3_Suscriptores,Estrato 4_Suscriptores,Estrato 5_Suscriptores,Estrato 6_Suscriptores,Industrial_Suscriptores,Comercial_Suscriptores,Oficial_Suscriptores,Otros_Suscriptores,Estrato 1_Consumo,Estrato 2_Consumo,Estrato 3_Consumo,Estrato 4_Consumo,Estrato 5_Consumo,Estrato 6_Consumo,Industrial_Consumo,Comercial_Consumo,Oficial_Consumo,Otros_Consumo,Estrato 1_Valor Consumo,Estrato 2_Valor Consumo,Estrato 3_Valor Consumo,Estrato 4_Valor Consumo,Estrato 5_Valor Consumo,Estrato 6_Valor Consumo,Industrial_Valor Consumo,Comercial_Valor Consumo,Oficial_Valor Consumo,Otros_Valor Consumo
0,0,2016,Julio,Urbano,NARINO,YACUANQUER,A.S.C INGENIERIA SOCIEDAD ANONIMA SA ESP.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,396.0,NaN,13790.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.908867e+05,NaN,7.135601e+06
1,1,2016,Julio,Urbano,NARINO,TANGUA,A.S.C INGENIERIA SOCIEDAD ANONIMA SA ESP.,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6915396.74,NaN,NaN,NaN
2,2,2016,Julio,Urbano,NARINO,SAN LORENZO,A.S.C INGENIERIA SOCIEDAD ANONIMA SA ESP.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16591.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.990229e+06
3,3,2016,Julio,Urbano,NARINO,SAN ANDRES DE TUMACO,A.S.C INGENIERIA SOCIEDAD ANONIMA SA ESP.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4252.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.047857e+06,NaN,NaN
4,4,2016,Julio,Urbano,NARINO,PASTO,A.S.C INGENIERIA SOCIEDAD ANONIMA SA ESP.,NaN,63.0,148.0,11.0,NaN,NaN,13.0,639.0,7.0,40.0,NaN,4239.0,10461.0,839.0,NaN,NaN,133262.0,692322.0,83234.0,372172.0,NaN,2041478.55,5290390.09,404057.69,NaN,NaN,61308218.80,3.211548e+08,36609891.46,1.630814e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626471,1003,2012,Abril,Rural,VALLE DEL CAUCA,GUACARI,VATIA S.A. E.S.P.,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15457.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4221190.00,NaN,NaN,NaN
626472,1004,2012,Abril,Rural,ATLANTICO,BARRANQUILLA,VATIA S.A. E.S.P.,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,824.0,621.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261824.00,197321.0,NaN,NaN,NaN,NaN,NaN
626473,1005,2012,Abril,Rural,SANTANDER,BARRANCABERMEJA,VATIA S.A. E.S.P.,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5915.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2429292.00,NaN,NaN,NaN
626474,1006,2012,Abril,Rural,TOLIMA,AMBALEMA,VATIA S.A. E.S.P.,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94564.0,1305.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27099206.00,4.458100e+05,NaN,NaN
626475,1007,2012,Abril,Rural,ANTIOQUIA,AMAGA,VATIA S.A. E.S.P.,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,341274.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43229448.00,NaN,NaN,NaN